-- What a commitment is. Configuration only — no progress, no verdict, no money.
-- Derived state has exactly one writer and it is settlement (AD-8); nothing in this
-- table is computed from anything else.
--
-- Conventions copied from 20260819120000_account_and_roles.sql: the table and its RLS
-- ship together, every function pins search_path, and `with check` calls the
-- table-reading role helper rather than the token-reading one. `lib/roles.test.ts`
-- fails the build on all three.

create type public.commitment_kind as enum ('do', 'abstain', 'open_ended');
create type public.commitment_cadence as enum ('daily', 'weekly_quota', 'daily_hours_quota');

create table public.commitment (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profile (id) on delete cascade,

  -- AD-4: generated by the client at the moment of the action and reused by retries, so
  -- a double-tap or a replayed offline write lands once. Unique across the table because
  -- a v4 UUID collision is not a case worth designing around.
  idempotency_key uuid not null unique,

  name text not null,
  kind public.commitment_kind not null,
  cadence public.commitment_cadence not null,

  -- Off unless deliberately turned on. Money is never a default.
  carries_penalty boolean not null default false,

  -- Cadence-specific targets. Which of these must be present is a constraint below, not
  -- a thing the form is trusted to remember.
  weekly_target integer,
  week_start_day integer,
  daily_minutes_target integer,

  -- Archive rather than delete. A commitment is referenced by every declaration, failed
  -- day and penalty that ever touched it; removing the row would break those references
  -- or silently rewrite the author's own history, and a ledger that cannot explain itself
  -- is worse than a stale row.
  archived_at timestamptz,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint commitment_name_not_blank
    check (length(btrim(name)) > 0),

  -- A weekly quota without a target is not a commitment, it is a half-filled form.
  constraint commitment_weekly_quota_targets check (
    (cadence = 'weekly_quota') = (weekly_target is not null)
    and (cadence = 'weekly_quota') = (week_start_day is not null)
  ),

  constraint commitment_daily_hours_target check (
    (cadence = 'daily_hours_quota') = (daily_minutes_target is not null)
  ),

  constraint commitment_weekly_target_range
    check (weekly_target is null or weekly_target between 1 and 7),

  -- ISO-8601 day numbering, 1 = Monday. Stored per commitment because a gym week and a
  -- work week may reasonably start on different days. Every boundary computed from it
  -- resolves in Asia/Ho_Chi_Minh (AD-6); no client ever derives the date.
  constraint commitment_week_start_range
    check (week_start_day is null or week_start_day between 1 and 7),

  -- Minutes at rest, always. The UI says hours; storing one unit means no rounding
  -- decision is ever made twice, and a focus session banking 90 minutes has somewhere
  -- exact to go.
  constraint commitment_minutes_positive
    check (daily_minutes_target is null or daily_minutes_target > 0)
);

comment on table public.commitment is
  'One thing the author has undertaken. Configuration only — progress and verdicts belong to settlement (AD-8).';

create index commitment_owner_active_idx
  on public.commitment (owner_id)
  where archived_at is null;

alter table public.commitment enable row level security;

create policy "commitment: read own"
  on public.commitment
  for select
  to authenticated
  using ((select auth.uid()) = owner_id);

-- `with check` uses role_from_table(), never role_from_token(). A token claim is stale
-- until the access token refreshes, and a stale role on a write creates a row that should
-- never have existed — which no later refresh undoes.
create policy "commitment: create own"
  on public.commitment
  for insert
  to authenticated
  with check ((select auth.uid()) = owner_id and public.role_from_table() = 'doer');

create policy "commitment: edit own"
  on public.commitment
  for update
  to authenticated
  using ((select auth.uid()) = owner_id)
  with check ((select auth.uid()) = owner_id and public.role_from_table() = 'doer');

-- Deliberately no delete policy. Removal is an update that sets archived_at, so the
-- history keeps its referent. The UI still calls it delete.

create function public.touch_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create trigger commitment_touch_updated_at
  before update on public.commitment
  for each row execute function public.touch_updated_at();

-- Reachable at /rest/v1/rpc otherwise. The advisor caught exactly this on the previous
-- migration's trigger function; a trigger fires regardless of EXECUTE grants.
revoke execute on function public.touch_updated_at() from public, anon, authenticated;
